site_name: Open Drone Stack
site_description: Modular open source drone system using ROS 2 and a REST API for high level mission control.
site_url: https://robotics-88.github.io/open-drone-docs
repo_url: https://github.com/robotics-88/open-drone-docs
repo_name: robotics-88/open-drone-docs

plugins:
  - search
  - mermaid2

theme:
  name: material
  logo: images/icon.png
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  favicon: images/icon.png
  font:
    text: Roboto

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details

nav:
  - Home: index.md
  - Setup Guide:
      - Overview: setup/index.md
      - IRL Drones:
          - Overview: setup/drones/index.md
          - Prerequisite hardware: setup/drones/hardware.md
          - Compatible drones: setup/drones/models.md
          - Flight stack setup: setup/drones/flightstack.md
          - Useful support software: setup/drones/support.md
          - Frontend: setup/drones/frontend.md
  - System:
      - Overview: system/index.md
      - Usage: system/usage.md
      - Architecture: 
          - ROS 2 nodes: system/architecture/nodes.md
          - State machine: system/architecture/statemachine.md
  - Development:
      - Overview: development/index.md
      - Missions: development/missions.md
      - Custom modules: development/modules.md
